services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_service
      - user_service
      - owner_service

  user_service:
    build:
      context: ./user_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/all_food_db.sqlite
    volumes:
      - ./user_service:/app
      - ./all_food_db.sqlite:/app/all_food_db.sqlite
    env_file:
      - .env

  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:////app/all_food_db.sqlite
    volumes:
      - ./auth_service:/app
      - ./all_food_db.sqlite:/app/all_food_db.sqlite
    env_file:
      - .env

  owner_service:
    build:
      context: ./owner_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:////app/all_food_db.sqlite
    volumes:
      - ./owner_service:/app
      - ./all_food_db.sqlite:/app/all_food_db.sqlite
    env_file:
      - .env